### ISSUE TITLE
Using ByteBuddy for proxy creation

### ISSUE THREAD

**Issue by sebthom** [ggeorgovassilis/spring-rest-invoker#25]
I am already using the awesome [ByteBuddy](http://bytebuddy.net/) library in a project. So it would be nice if I could easily configure the invoker to use ByteBuddy instead of cglib for proxy generation.

Maybe the project could use this library instead of directly depending on cglib for (opaque) proxies: https://github.com/neoremind/dynamic-proxy

**Comment by ggeorgovassilis** [comment]
Thanks @sebthom for the FR. I also noticed several projects switching to BB but don't have any experience with it. Would you mind creating a proof of concept e.g. by renaming CglibProxyFactory to ByteBuddyProxyFactory and implementing it with BB? I'd wire that then into the repo so that it can coexist with other proxying mechanisms

**Comment by ggeorgovassilis** [comment]
Closed due to lack of interest
